apiVersion: v1
kind: PersistentVolume
metadata:
  name: delivery-pv
  labels:
    name: delivery-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: postgresdata
    type: DirectoryOrCreate