apiVersion: v1
kind: Service
metadata:
  name: svc-api-webserver
spec:
  type: LoadBalancer
  ports:
    - port: 3000      
      nodePort: 31000
      targetPort: 3000
  selector:
    app: api-delivery