apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delivery-db-pvc
  labels:
    name: delivery-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage   